const draftKey='shorts-studio-draft-v1';
const draftStatus=document.querySelector('#draftStatus');
const briefForm=document.querySelector('#briefForm');
let draftTimer=null;
function collectDraft(){const data={};new FormData(briefForm).forEach((value,key)=>data[key]=value);return data}
function saveDraft(showMessage=true){localStorage.setItem(draftKey,JSON.stringify({savedAt:new Date().toISOString(),values:collectDraft()}));if(showMessage)draftStatus.textContent='현재 입력을 저장했습니다.'}
function loadDraft(){const saved=JSON.parse(localStorage.getItem(draftKey)||'null');if(!saved){draftStatus.textContent='저장된 입력이 없습니다.';return}[...briefForm.elements].filter(field=>field.type==='checkbox').forEach(field=>field.checked=false);Object.entries(saved.values).forEach(([name,value])=>{const field=briefForm.elements.namedItem(name);if(!field)return;if(field.type==='checkbox')field.checked=true;else field.value=value});document.querySelector('#industry').dispatchEvent(new Event('change',{bubbles:true}));briefForm.dispatchEvent(new Event('input',{bubbles:true}));draftStatus.textContent='저장된 입력을 불러왔습니다.'}
briefForm.addEventListener('input',()=>{clearTimeout(draftTimer);draftStatus.textContent='입력 변경됨';draftTimer=setTimeout(()=>{saveDraft(false);draftStatus.textContent='자동저장 완료'},700)});
document.querySelector('#saveDraft').addEventListener('click',()=>saveDraft(true));
document.querySelector('#loadDraft').addEventListener('click',loadDraft);
const examples={hair:{businessName:'더엠헤어',product:'손상모 복구 클리닉',audience:'염색과 펌으로 모발이 손상된 고객',region:'성수동 주거·오피스 상권',contactInfo:'네이버 예약, 평일 10-20시',sellingPoint:'예약제로 운영하며 시술 전 상담 제공'},food:{businessName:'우리동네식당',product:'대표 점심 메뉴',audience:'빠르고 든든한 점심을 찾는 직장인',region:'역세권 오피스 상권',contactInfo:'매장 방문, 평일 점심 운영',sellingPoint:'실제 제공 메뉴와 운영시간 확인 필요'},cafe:{businessName:'동네카페',product:'시그니처 디저트',audience:'오후 간식과 휴식 공간을 찾는 고객',region:'주거 상권',contactInfo:'매장 방문',sellingPoint:'당일 판매 구성은 매장 확인'}};
document.querySelector('#fillExample').addEventListener('click',()=>{const industry=document.querySelector('#industry').value;const example=examples[industry]||{businessName:'우리동네가게',product:'대표 서비스',audience:'지역 고객',region:'지역 상권',contactInfo:'방문 또는 문의',sellingPoint:'실제 제공 범위 확인 필요'};Object.entries(example).forEach(([name,value])=>{const field=briefForm.elements.namedItem(name);if(field)field.value=value});briefForm.dispatchEvent(new Event('input',{bubbles:true}));draftStatus.textContent='업태 예시를 입력했습니다. 실제 정보로 수정하세요.'});
document.querySelector('#toggleCrew').addEventListener('click',event=>{const shell=document.querySelector('.game-shell');const collapsed=shell.classList.toggle('crew-collapsed');event.currentTarget.textContent=collapsed?'작업실 펼치기':'작업실 접기';localStorage.setItem('shorts-studio-crew-collapsed',collapsed?'1':'0')});
if(localStorage.getItem('shorts-studio-crew-collapsed')==='1'){document.querySelector('.game-shell').classList.add('crew-collapsed');document.querySelector('#toggleCrew').textContent='작업실 펼치기'}
document.querySelector('#exportPlan').addEventListener('click',()=>{const result=document.querySelector('#result');if(result.classList.contains('empty')){draftStatus.textContent='먼저 기획안을 생성하세요.';return}const title=(document.querySelector('#businessName').value.trim()||'숏츠기획')+'_30초기획서.txt';const blob=new Blob([result.innerText],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=title;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);draftStatus.textContent='기획서를 저장했습니다.'});
if(localStorage.getItem(draftKey))draftStatus.textContent='저장된 작업 있음';
const mobileUrl=document.querySelector('#mobileUrl');
if(location.hostname.endsWith('github.io'))mobileUrl.textContent=location.href.split('#')[0]+'#maker';
else fetch('/health').then(response=>response.json()).then(status=>{mobileUrl.textContent=status.mobileUrl||location.href}).catch(()=>{mobileUrl.textContent=location.href.split('#')[0]+'#maker'});
document.querySelector('#copyMobileUrl').addEventListener('click',async event=>{const value=mobileUrl.textContent;if(!value.startsWith('http'))return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(value);else{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}event.currentTarget.textContent='복사 완료';setTimeout(()=>event.currentTarget.textContent='주소 복사',1500)}catch{event.currentTarget.textContent='주소를 길게 눌러 복사'}});
